// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcmgKFy8Vj34bP56D4AGoT_6GDDhD5LTI',
    appId: '1:802621606380:web:10d7c15ae11a9eff0498c9',
    messagingSenderId: '802621606380',
    projectId: 'tera-ac1e8',
    authDomain: 'tera-ac1e8.firebaseapp.com',
    storageBucket: 'tera-ac1e8.firebasestorage.app',
    measurementId: 'G-CNQS8Z2004',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATFU4wc8tN36gCHWWK_7qB7PRujgrl1Oc',
    appId: '1:802621606380:android:a8d909d5592164d70498c9',
    messagingSenderId: '802621606380',
    projectId: 'tera-ac1e8',
    storageBucket: 'tera-ac1e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6LbKEEEL_CDLQMi7_uili-8z3Hqo95DU',
    appId: '1:802621606380:ios:fc5dc648bb299d480498c9',
    messagingSenderId: '802621606380',
    projectId: 'tera-ac1e8',
    storageBucket: 'tera-ac1e8.firebasestorage.app',
    iosBundleId: 'com.example.teraApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6LbKEEEL_CDLQMi7_uili-8z3Hqo95DU',
    appId: '1:802621606380:ios:fc5dc648bb299d480498c9',
    messagingSenderId: '802621606380',
    projectId: 'tera-ac1e8',
    storageBucket: 'tera-ac1e8.firebasestorage.app',
    iosBundleId: 'com.example.teraApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcmgKFy8Vj34bP56D4AGoT_6GDDhD5LTI',
    appId: '1:802621606380:web:10f0eb98f2d559400498c9',
    messagingSenderId: '802621606380',
    projectId: 'tera-ac1e8',
    authDomain: 'tera-ac1e8.firebaseapp.com',
    storageBucket: 'tera-ac1e8.firebasestorage.app',
    measurementId: 'G-31KF2ZEGKE',
  );

}